# Fast Fuzzy Filter
Using Fast Fuzzy Search to filter Potential Event-containing news. The main goal is to reduce the training time by achieving a more reduced but higher quality news set.

In [ ]:
from rapidfuzz import fuzz
import pandas as pd
import json

In [ ]:
# this cell is for loading the first version of fast fuzzy search filtered news, which we generated with the initial keyword set
df = pd.read_csv("filtered_news/filtered_news_with_keywords.csv",index_col=0)
df

,Date,Article_title,Stock_symbol,Url,Article,MatchedKeyword,MatchScore
1,2021-10-19 00:00:00 UTC,"""9 Foolish Truths That I Hold to Be Self-Evident""",NVDA,https://www.nasdaq.com/articles/9-foolish-trut...,"If you're a longtime listener to this podcast,...",covid,100.0
2,2020-03-25 00:00:00 UTC,"""Airlines"" Didn't Waste All Their Cash Flow on...",AAL,https://www.nasdaq.com/articles/airlines-didnt...,"Last Monday, Bloomberg reported that the top f...",covid,100.0
3,2018-09-22 00:00:00 UTC,"""Alexa, Make Me Money"": Conversational AI Prep...",ORCL,https://www.nasdaq.com/articles/alexa-make-me-...,We've already gotten comfortable with digital ...,new legislation,100.0
5,2022-08-27 00:00:00 UTC,"""Ape"" Into AMC? Buy These Explosive Growth Sto...",BILL,https://www.nasdaq.com/articles/ape-into-amc-b...,"Some investors ""aped"" into AMC Entertainment (...",wildfire,100.0
10,2023-08-04 00:00:00 UTC,"""Big Tech"" Earnings Review: ETFs in Focus",AAPL,https://www.nasdaq.com/articles/big-tech-earni...,"Since late July, five major tech companies fro...",iphone,100.0
...,...,...,...,...,...,...,...
662384,2022-03-04 00:00:00 UTC,“Pixelmon” a Dud… And 4 Other Surprises This Week,XOM,https://www.nasdaq.com/articles/pixelmon-a-dud...,"InvestorPlace - Stock Market News, Stock Advic...",invasion,100.0
662386,2021-09-15 00:00:00 UTC,“Yes in My Backyard”: How the Shift from China...,CC,https://www.nasdaq.com/articles/yes-in-my-back...,"InvestorPlace - Stock Market News, Stock Advic...",missile,100.0
662387,2021-08-24 00:00:00 UTC,‪11 Recovery Stocks That Could Get a Vaccine S...,GLPI,https://www.nasdaq.com/articles/11-recovery-st...,Recovery stocks were all the rage heading into...,covid,100.0
662389,2022-05-23 00:00:00 UTC,📈 Two Charts Show That Biotech Is in for a Sto...,MSFT,https://www.nasdaq.com/articles/two-charts-sho...,"InvestorPlace - Stock Market News, Stock Advic...",violent,100.0
662390,2022-05-23 00:00:00 UTC,🔋 The Forever Battery “Gold Rush” Has Arrived,MS,https://www.nasdaq.com/articles/the-forever-ba...,"InvestorPlace - Stock Market News, Stock Advic...",covid,100.0

## Designing the keyword list
- Be careful, do not to include many company and country names (they may result in poor filtering)

In [ ]:
with open("new_events.json") as events_json:
    events = json.load(events_json)

event_titles = [event["text"] for year in events for event in events[year]]
event_titles

In [ ]:
# v1 KEYWORD LIST, less strict
event_keywords = [
    # POLITICAL - leadership changes
    "general election", "referendum", "runoff", "abdication","Secretary",
    "coronation", "monarch", "assassin","muerder", "coup de etat", "junta","political", "royal", "the king","the queen",
    "House of Representatives","Chancellor", "Senate","revoke",

    # POLITICAL - wars and armed conflicts
    " war ", "invasion", "occupation", "bombing", "terrorism", "attack","Armed Forces",
    "civil war", "insurgency", "rebellion", "uprising","battle",
    "airstrike", "missile", "ceasefire", "treaty", "accord", "violent", "terrorist","rebels","military","Hamas","Al Qaeda","Gaza",

    # POLITICAL - economy
    "recession", "crisis", "currency change",
    "trade agreement", "customs union", "fraud", "embezzlement", "corruption", "scandal", "Euro enters circulation","East African Community",

    # POLITICAL - climate and environment policies
    "paris agreement", "kyoto protocol", "cop", "ipcc", "unfccc", "climate conference",

    # POLITICAL - legal milestones
    "constitution", "legal","legislation","law", "court","independence","reform","summit","trial",

    # POLITICAL - social movements
    "protest", "riot", "revolution", "social movement", "social tension", "violence","lgtb","rights","black lifes","unrest","women",

    # POLITICAL - diplomatic relations
    "Assembly", "United Nations", "nato", "g7", "g20", "bloc","diplomatic","peace agreement",

    # NON POLITICAL - disasters and crisis
    "earthquake", "tsunami", "hurricane", "flood", "eruption", "fire","polio", "environmental disaster","environmental"
    "pandemic", "epidemic", "covid", "sars", "coronavirus","ebola", "outbreak", "quarantine", "massacre",
    "crash", "derailment", "explosion", "storm", "Southern Leyte mudslide", "Cyclone", "shoot","SAG-AFTRA","Typhoon","crush",

    # NON POLITICAL - science & tech
    "spacex", "vaccine", "crispr", "chatgpt launch", "artificial intelligence","moon","asteroid","satellite","spacecraft",
    "iphone", "android", "discovery","ipod","invention","collision","scien","extinct","climate change","global warning","pollution","space exploration",

    # NON POLITICAL - cultural
    "olympics", "worldcup", "eurovision", "grammy", "tiktok",
    "viral", "church","World Series","pope","world record","championship",

    # NON POLITICAL - cultural (births & deaths)
    "death","dies","birth",

    # NON POLITICAL - corporate
    "company founded", "startup launched", "new venture","bankruptcy", "fraud", "Pandora Papers",
    
    # dangerous words (may apppear too many times)
    # "Facebook", 
    # "Twitter", "Spotify",
    # "Google",
    # "Schengen", "European Union", "World Trade Organization","acquired", "Eurasian Economic Union","trade area","trade organization","agreement",
    # "founded","releas","launch","collaps"
    # "NASA",
    # "Israel","Palestina",
    # "Jeff Bezos",
    # "Google",
    # "kill", "weapon", "Bitcoin","crypto",
]


# v2 KEYWORD LIST, more strict and refined after testing v1
event_keywords = [
    # POLITICAL - leadership changes
    "general elections", "referendum", "abdicate", "brexit","General Secretary","presidential election","inaugurated as President",
    "coronation", "monarch", "assassin","murder", "coup d'etat", "the king","Queen Margrethe","First Secretary",
    "House of Representatives","Chancellor", "Senate","Buckingham Palace","royal family","Prince George of Wales","Elizabeth II","Charles III",

    # POLITICAL - wars and armed conflicts
    "invasion","bombing", "terrorism","Armed Forces","Rose Revolution","Tulip Revolution","drug war","Tigray War","Taliban offensive",
    "civil war", "uprising","Virginia Tech shooting","Colorado shooting","Osama bin Laden","Muammar Gaddafi",
    "air strike", "missile", "ceasefire", "treaty", "terrorist","Hamas","Al Qaeda","Gaza","armed conflict","mass killings","School shooting",
    "Operation 1027",

    # POLITICAL - economy
    "trade agreement", "Euro enters circulation","Guayana Esequiba crisis","Ecuadorian political crisis","corruption scandal",

    # POLITICAL - climate and environment policies
    "paris agreement", "kyoto protocol", "ipcc", "unfccc", "climate change conference","COP26","COP28","summit","oil spill",
    "Intergovernmental Panel on Climate Change", "Sixth Assessment Report", "Environment Programme",

    # POLITICAL - legal milestones
    "constitution", "new legislation","legalization", "Supreme Court","pension reform","judicial reform","Independence of Montenegro",

    # POLITICAL - social movements
    "protest", "riots", "social movement", "social tension", "lgtb","civil rights","civil liberties","black lifes"," unrest ","George Floyd","Hong Kong protest",
    "Geneva Consensus Declaration on Promoting Women's Health and Strengthening the Family","International Organization for Migration","Human Rights",

    # POLITICAL - diplomatic relations
    "Assembly", "United Nations", " nato ","diplomatic","peace agreement",

    # NON POLITICAL - disasters and crisis
    "earthquake", "tsunami", "hurricane", "eruption", "wildfire","polio", "environmental disaster","Storm Uri","Storm Daniel",
    "epidemic","ebola", "quarantine", "lock down", "massacre","Rana Plaza collaps",
    "Southern Leyte mudslide", "Cyclone", "mass shooting","SAG-AFTRA","Typhoon","natural disaster","factory fire",
    "public health emergency","COVID-19 protest","covid protest","Tropical Storm","Monkeypox",

    # NON POLITICAL - science & tech
    "spacex", "malaria vaccine", "chatgpt", "deepmind","moon","asteroid","spacecraft","Royal Astronomical Society",
    "first iphone", "scientific discovery","first iPod","invention","collision","Scientific breakthrough","Scientific milestone",
    "climate change","global warming","space exploration","AlphaGo","Gotthard Base Tunnel","Event Horizon Telescope",
    "nuclear scientist","Protein folding","AlphaFold","Arecibo Telescope","Arecibo Observatory","Blue Origin","National Ignition Facility",

    # NON POLITICAL - cultural
    "olympics", "worldcup", "eurovision", "grammy","World Series","championship","Academy Award",

    # NON POLITICAL - cultural (births & deaths)

    # NON POLITICAL - corporate and others
    "startup launch", "Chapter 11 bankruptcy", "Pandora Papers","Panama Papers","International Consortium of Investigative Journalists","Elon Musk purchases Twitter",
    "Schengen", "European Union", "World Trade Organization", "Eurasian Economic Union","World Health Organization", 
    "North Atlantic Treaty Organization","East African Community","Treaty on the Prohibition of Nuclear Weapons","Istanbul Convention",
    "International Criminal Court","Bangsamoro Autonomous Region","Regional Comprehensive Economic Partnership","RCEP","Brereton Report",
    "NASA","Notre-Dame Cathedral","United States Space Force","Royal Australian Air Force","Human Rights Council","Commission on Narcotic Drugs",
    "Israel","Palestina","Yeonpyeong","Hugo Chavez","Nelson Mandela","funeral","Michael Brown","African Continental Free Trade Area","Champlain Towers","International Space Station",
    "killing all", "Bitcoin","company merger","company acquisition","plane crash","BRICS","Avatar","Grand Theft Auto V","ship Ever Given","National Independence","United Kingdom government crises",
]

## Run the fast fuzzy search algorithm

In [36]:
# load news dataframe
df = pd.read_csv("filtered_news/filtered_news_only_SP_no_duplicates_v8.csv")

In [18]:
df = df.sample(10000)

df["Article"]

480956    Wall Street analysts expect Oracle (ORCL) to p...
40693     [Editor’s note: “7 Tech Industry Dividend Stoc...
195875    Stocks opened higher Tuesday, as the Dow rebou...
93546     Atlas Resource Partners, L.P. ( ARP ) will beg...
535217    For Immediate Release\nChicago, IL - December ...
                                ...
415706    Among the underlying components of the Russell...
634322    What happened\nShares of Kratos Defense & Secu...
342139    Investors with an interest in REIT and Equity ...
179603    We have retained our Neutral recommendation on...
523153    InvestorPlace - Stock Market News, Stock Advic...
Name: Article, Length: 10000, dtype: object

In [51]:
# too slow!!!
# texts = df["Article"].tolist()

# threshold = 95  

# def filter_texts(texts, keywords, threshold=80):
#     results = []
#     for text in texts:
#         for kw in keywords:
#             if fuzz.partial_ratio(kw.lower(), text.lower()) >= threshold:
#                 results.append((text,kw.lower(),fuzz.partial_ratio(kw.lower(), text.lower())))
#                 break
#     return results

# filtered_texts = filter_texts(texts, event_keywords, threshold)

# # for text in filtered_texts:
# #     print()
# #     for i in range(len(text)):
# #         print(text[i])
# #     print(text)

# print(len(filtered_texts))

In [ ]:
# faster!
threshold = 95
keywords_lower = [kw.lower() for kw in event_keywords]

def match_keywords(text):
    text_lower = text.lower()
    for kw in keywords_lower:
        if kw in text_lower:
            return pd.Series([kw, 100])
        score = fuzz.partial_ratio(kw, text_lower)
        if score >= threshold:
            return pd.Series([kw, score])
    return pd.Series([None, None])

df[["MatchedKeyword", "MatchScore"]] = df["Article"].apply(match_keywords)

filtered_df = df[df["MatchedKeyword"].notna()]

print(len(filtered_df))

82373

In [39]:
print(len(event_keywords))
filtered_df.MatchedKeyword.value_counts().head(20)

202

MatchedKeyword
chatgpt                  8986
referendum               5695
bitcoin                  5352
rcep                     4442
hurricane                3642
european union           3167
invasion                 3095
brexit                   2904
senate                   2850
israel                   2617
assembly                 2457
summit                   2164
presidential election    2034
moon                     1751
missile                  1684
climate change           1592
the king                 1440
protest                  1351
legalization             1158
wildfire                 1146
Name: count, dtype: int64

In [35]:
keyword = "summit"
df[df["MatchedKeyword"] == keyword].Article.values

array(["Fintel reports that on October 30, 2023, Summit Insights Group upgraded their outlook for Western Digital (NASDAQ:WDC) from Hold to Buy .\nAnalyst Price Forecast Suggests 23.84% Upside\nAs of October 5, 2023, the average one-year price target for Western Digital is 48.26. The forecasts range from a low of 31.31 to a high of $63.00. The average price target represents an increase of 23.84% from its latest reported closing price of 38.97.\nSee our leaderboard of companies with the largest price target upside.\nThe projected annual revenue for Western Digital is 16,108MM, an increase of 42.15%. The projected annual non-GAAP EPS is 4.08.\nWhat is the Fund Sentiment?\nThere are 1130 funds or institutions reporting positions in Western Digital. This is a decrease of 21 owner(s) or 1.82% in the last quarter. Average portfolio weight of all funds dedicated to WDC is 0.18%, a decrease of 1.23%. Total shares owned by institutions decreased in the last three months by 4.99% to 295,395K shares.\nThe put/call ratio of WDC is 1.03, indicating a bearish outlook.\nWhat are Other Shareholders Doing?\nPrice T Rowe Associates holds 24,029K shares representing 7.41% ownership of the company. In it's prior filing, the firm reported owning 22,595K shares, representing an increase of 5.97%. The firm decreased its portfolio allocation in WDC by 0.33% over the last quarter.\nNomura Holdings holds 12,491K shares representing 3.85% ownership of the company. In it's prior filing, the firm reported owning 10,606K shares, representing an increase of 15.09%. The firm increased its portfolio allocation in WDC by 0.72% over the last quarter.\nVTSMX - Vanguard Total Stock Market Index Fund Investor Shares holds 9,970K shares representing 3.08% ownership of the company. In it's prior filing, the firm reported owning 9,896K shares, representing an increase of 0.75%. The firm decreased its portfolio allocation in WDC by 6.40% over the last quarter.\nVictory Capital Management holds 9,708K shares representing 2.99% ownership of the company. In it's prior filing, the firm reported owning 9,427K shares, representing an increase of 2.89%. The firm increased its portfolio allocation in WDC by 63.07% over the last quarter.\nTRMCX - T. Rowe Price Mid-Cap Value Fund holds 8,007K shares representing 2.47% ownership of the company. In it's prior filing, the firm reported owning 7,967K shares, representing an increase of 0.50%. The firm decreased its portfolio allocation in WDC by 2.07% over the last quarter.\nWestern Digital Background Information\n(This description is provided by the company.)\nWestern Digital creates environments for data to thrive. As a leader in data infrastructure, the company is driving the innovation needed to help customers capture, preserve, access and transform an ever-increasing diversity of data. Everywhere data lives, from advanced data centers to mobile sensors to personal devices, our industry-leading solutions deliver the possibilities of data.\nFintel is one of the most comprehensive investing research platforms available to individual investors, traders, financial advisors, and small hedge funds.\nOur data covers the world, and includes fundamentals, analyst reports, ownership data and fund sentiment, options sentiment, insider trading, options flow, unusual options trades, and much more. Additionally, our exclusive stock picks are powered by advanced, backtested quantitative models for improved profits.\nClick to Learn More\nThis story originally appeared on Fintel.\nThe views and opinions expressed herein are the views and opinions of the author and do not necessarily reflect those of Nasdaq, Inc.",

In [9]:
df.head(45)

,Date,Article_title,Stock_symbol,Url,Article,MatchedKeyword,MatchScore
1,2021-10-19 00:00:00 UTC,"""9 Foolish Truths That I Hold to Be Self-Evident""",NVDA,https://www.nasdaq.com/articles/9-foolish-trut...,"If you're a longtime listener to this podcast,...",covid,100.0
2,2020-03-25 00:00:00 UTC,"""Airlines"" Didn't Waste All Their Cash Flow on...",AAL,https://www.nasdaq.com/articles/airlines-didnt...,"Last Monday, Bloomberg reported that the top f...",covid,100.0
3,2018-09-22 00:00:00 UTC,"""Alexa, Make Me Money"": Conversational AI Prep...",ORCL,https://www.nasdaq.com/articles/alexa-make-me-...,We've already gotten comfortable with digital ...,new legislation,100.0
5,2022-08-27 00:00:00 UTC,"""Ape"" Into AMC? Buy These Explosive Growth Sto...",BILL,https://www.nasdaq.com/articles/ape-into-amc-b...,"Some investors ""aped"" into AMC Entertainment (...",wildfire,100.0
10,2023-08-04 00:00:00 UTC,"""Big Tech"" Earnings Review: ETFs in Focus",AAPL,https://www.nasdaq.com/articles/big-tech-earni...,"Since late July, five major tech companies fro...",iphone,100.0
11,2017-12-07 00:00:00 UTC,"""Bitcoin Stocks"" Get a New Member as Cboe Laun...",CME,https://www.nasdaq.com/articles/bitcoin-stocks...,"The price of bitcoin, the oldest and largest c...",extinct,100.0
12,2023-09-13 00:00:00 UTC,"""Blockbuster Status"": 3 Bios to Buy and Hold",ABBV,https://www.nasdaq.com/articles/blockbuster-st...,Profitability in the Biotech Industry is Hard ...,chatgpt,100.0
17,2022-03-24 00:00:00 UTC,"""Chip Rally,"" NATO Results, Drive Market Indexes",NVDA,https://www.nasdaq.com/articles/chip-rally-nat...,Markets kept their early morning gains and — a...,nato,100.0
21,2020-09-04 00:00:00 UTC,"""Dogs of the Dow"" Update: Buy These 5.9% Divid...",CVX,https://www.nasdaq.com/articles/dogs-of-the-do...,I dig dividend stocks that keep a low profile....,covid,100.0
23,2016-06-23 00:00:00 UTC,"""Finding Dory"" Had a Record-Breaking $135.1 Mi...",CMCSA,https://www.nasdaq.com/articles/finding-dory-h...,Walt Disney Co. 's(NYSE: DIS) Finding Dory rak...,civil war,100.0
24,2015-08-27 00:00:00 UTC,"""Flash Boys"" Inspired Lawsuit on Barclays Reje...",MS,https://www.nasdaq.com/articles/flash-boys-ins...,With the dismissal of an impending court case ...,fraud,100.0
26,2014-12-03 00:00:00 UTC,"""Frozen"" Topples Barbie Off The Top Toy Pedestal",HAS,https://www.nasdaq.com/articles/frozen-topples...,Barbie is no longer the queen of the toy box. ...,the queen,100.0
28,2014-11-04 00:00:00 UTC,"""Goodbye Mr. Jones"": The End Of The Dow As An ...",KO,https://www.nasdaq.com/articles/goodbye-mr-jon...,By The Intercollegiate Finance Journal :\nBy C...,the king,100.0
32,2020-07-11 00:00:00 UTC,"""Hamilton"" Did More for Disney+ Than Increase ...",DIS,https://www.nasdaq.com/articles/hamilton-did-m...,Disney (NYSE: DIS) saw a surge in sign-ups for...,independence,100.0
33,2020-07-06 00:00:00 UTC,"""Hamilton"" Drives a Huge Surge in Demand for D...",DIS,https://www.nasdaq.com/articles/hamilton-drive...,Lin-Manuel Miranda's smash Broadway musical Ha...,covid,100.0
35,2020-04-22 00:00:00 UTC,"""Historic"" trading volumes drive Nasdaq's prof...",NDAQ,https://www.nasdaq.com/articles/historic-tradi...,April 22 (Reuters) - Transatlantic exchange op...,coronavirus,100.0
36,2020-12-05 00:00:00 UTC,"""If You Don't Have an Estate Plan, Please, Jus...",KSS,https://www.nasdaq.com/articles/if-you-dont-ha...,"In this episode of Motley Fool Answers, Alison...",covid,100.0
37,2021-06-28 00:00:00 UTC,"""Industry Focus: Energy"" Interviews Tracy Shuc...",XOM,https://www.nasdaq.com/articles/industry-focus...,"In this episode of Industry Focus: Energy, ene...",environmental,100.0
44,2023-10-20 00:00:00 UTC,"""Magnificent Seven"" Earnings Underway: ETFs in...",TSLA,https://www.nasdaq.com/articles/magnificent-se...,We are in the thick of the third-quarter earni...,iphone,100.0
45,2018-07-03 00:00:00 UTC,"""MarketFoolery"" Mailbag Day: Advice for Novice...",NKE,https://www.nasdaq.com/articles/marketfoolery-...,"In this MarketFoolery podcast, host Chris Hill...",independence,100.0
49,2022-01-07 00:00:00 UTC,"""Motley Fool Money"" 2022 Investing Preview",NKE,https://www.nasdaq.com/articles/motley-fool-mo...,"What's so exciting about home improvement, hea...",riots,100.0
50,2023-01-04 00:00:00 UTC,"""Motley Fool Money"" 2023 Investing Preview",DEA,https://www.nasdaq.com/articles/motley-fool-mo...,"In this podcast, Motley Fool senior analysts J...",invasion,100.0
51,2022-12-03 00:00:00 UTC,"""Motley Fool Money"" Discusses Best Side Dishes...",DIS,https://www.nasdaq.com/articles/motley-fool-mo...,"In this podcast, Motley Fools Chris Hill, Bill...",rebellion,100.0
52,2022-09-07 00:00:00 UTC,"""Motley Fool Money"" Fall Preview for Investors",QCOM,https://www.nasdaq.com/articles/motley-fool-mo...,"In this podcast, Motley Fool senior analysts E...",olympics,100.0
53,2023-10-31 00:00:00 UTC,"""Motley Fool Money"" on the Road",NDAQ,https://www.nasdaq.com/articles/motley-fool-mo...,"In this podcast, Motley Fool host Dylan Lewis ...",covid,100.0
55,2023-04-14 00:00:00 UTC,"""Natty"" Is Down Big. What Comes Next Is More E...",HP,https://www.nasdaq.com/articles/natty-is-down-...,"We contrarians, we're not ashamed to admit, ma...",covid,100.0
62,2020-05-23 00:00:00 UTC,"""Raised to Be Poor""",DIS,https://www.nasdaq.com/articles/raised-to-be-p...,"In this episode of Rule Breaker Investing, Mot...",ipod,100.0
64,2023-11-03 00:00:00 UTC,"""Reduce Excessive Credit Card Fees"": Why Visa ...",DFS,https://www.nasdaq.com/articles/reduce-excessi...,Congress is putting major credit card processo...,senate,100.0
66,2022-09-10 00:00:00 UTC,"""Rule Breaker Investing"" August Mailbag: Talki...",OKTA,https://www.nasdaq.com/articles/rule-breaker-i...,"If you want to be better with money, the best ...",independence,100.0
67,2023-07-15 00:00:00 UTC,"""Rule Breaker Investing"" Market Cap Game Show:...",TSLA,https://www.nasdaq.com/articles/rule-breaker-i...,To catch full episodes of all The Motley Fool'...,independence,100.0
68,2022-12-10 00:00:00 UTC,"""Rule Breaker Investing"" November Mailbag: Gra...",CASY,https://www.nasdaq.com/articles/rule-breaker-i...,To catch full episodes of all The Motley Fool'...,iphone,100.0
69,2022-10-29 00:00:00 UTC,"""Rule Breaker Investing"" October Mailbag: List...",AAPL,https://www.nasdaq.com/articles/rule-breaker-i...,In this mailbag edition of Rule Breaker Invest...,ipod,100.0
70,2023-01-14 00:00:00 UTC,"""Rule Breaker Investing"": Old, New, Borrowed, ...",TSLA,https://www.nasdaq.com/articles/rule-breaker-i...,"In this podcast, Motley Fool co-founder David ...",covid,100.0
72,2020-12-24 00:00:00 UTC,"""Shark Tank"" Star Kevin O'Leary Talks About Fi...",DOCU,https://www.nasdaq.com/articles/shark-tank-sta...,This week's installment of Industry Focus: Fin...,independence,100.0
73,2023-09-27 00:00:00 UTC,"""Shark Tank"" Star Kevin O'Leary Thinks Stocks ...",BANC,https://www.nasdaq.com/articles/shark-tank-sta...,Kevin O'Leary's nickname is Mr. Wonderful. But...,covid,100.0
74,2016-05-09 00:00:00 UTC,"""Sheik""-Up in Saudi Oil Leadership",GS,https://www.nasdaq.com/articles/sheik-saudi-oi...,"Monday, May 9, 2016\nStocks are indicated to s...",the king,100.0
75,2022-09-16 00:00:00 UTC,"""Snowflake"" Trading Continues, and It's Still ...",FDX,https://www.nasdaq.com/articles/snowflake-trad...,"Friday, September 16, 2022\n\nLook, no one thi...",covid,100.0
76,2023-07-13 00:00:00 UTC,"""Soft Landing"" Ahead? I Think So. Here Are the...",DE,https://www.nasdaq.com/articles/soft-landing-a...,One of the most difficult things for me in 202...,independence,100.0
80,2021-03-05 00:00:00 UTC,"""Spoofing"" Lawsuit Against Bank of America, Mo...",MS,https://www.nasdaq.com/articles/spoofing-lawsu...,Bank of America (NYSE: BAC) and Morgan Stanley...,fraud,100.0
81,2021-11-13 00:00:00 UTC,"""Squid Game"" Passes ""Game of Thrones"" For Popu...",T,https://www.nasdaq.com/articles/squid-game-pas...,The most popular series on Netflix Inc (NASDAQ...,tiktok,100.0
83,2014-09-14 00:00:00 UTC,"""Star Wars 7"" Is Still a Year Away; Here’s How...",HAS,https://www.nasdaq.com/articles/star-wars-7-st...,Star Wars Rebels tells the story of the early ...,rebellion,100.0
92,2023-01-03 00:00:00 UTC,"""Technofundamentals"": 3 Top-Ranked Stocks with...",CELH,https://www.nasdaq.com/articles/technofundamen...,Earnings estimate revisions are the most power...,covid,100.0
93,2020-09-08 00:00:00 UTC,"""Tenet"" Fails to Save the Multiplex",T,https://www.nasdaq.com/articles/tenet-fails-to...,There was a lot riding on Christopher Nolan th...,covid,100.0
94,2020-08-25 00:00:00 UTC,"""The Eight Hundred"" Is a Hit for IMAX in China",T,https://www.nasdaq.com/articles/the-eight-hund...,Movie theaters in China are returning to norma...,covid,100.0
95,2022-09-19 00:00:00 UTC,"""The Era of the Gene-Edited Human Is Here""",GILD,https://www.nasdaq.com/articles/the-era-of-the...,"In this podcast, Motley Fool proucer Ricky Mul...",crispr,100.0

In [ ]:
# save the result
filtered_df.to_csv("filtered_news/filtered_news_with_keywords_v2.csv")
filtered_df.head(45)

,Date,Article_title,Stock_symbol,Url,Article,MatchedKeyword,MatchScore
1,2021-10-19 00:00:00 UTC,"""9 Foolish Truths That I Hold to Be Self-Evident""",NVDA,https://www.nasdaq.com/articles/9-foolish-trut...,"If you're a longtime listener to this podcast,...",summit,100.0
3,2018-09-22 00:00:00 UTC,"""Alexa, Make Me Money"": Conversational AI Prep...",ORCL,https://www.nasdaq.com/articles/alexa-make-me-...,We've already gotten comfortable with digital ...,new legislation,100.0
5,2022-08-27 00:00:00 UTC,"""Ape"" Into AMC? Buy These Explosive Growth Sto...",BILL,https://www.nasdaq.com/articles/ape-into-amc-b...,"Some investors ""aped"" into AMC Entertainment (...",wildfire,100.0
6,2022-12-29 00:00:00 UTC,"""Avatar"" Sequel Crosses $1 Billion at the Box ...",DIS,https://www.nasdaq.com/articles/avatar-sequel-...,"In this video, I will talk about Walt Disney (...",avatar,100.0
7,2019-06-26 00:00:00 UTC,"""Avengers: Endgame"" Has Already Beaten Avatar'...",DIS,https://www.nasdaq.com/articles/avengers%3A-en...,"Almost since its record-setting debut, Avenger...",summit,100.0
8,2019-06-19 00:00:00 UTC,"""Avengers: Endgame"" Takes One Last Run at the ...",DIS,https://www.nasdaq.com/articles/avengers%3A-en...,It looks like Avengers: Endgame will snag that...,avatar,100.0
11,2017-12-07 00:00:00 UTC,"""Bitcoin Stocks"" Get a New Member as Cboe Laun...",CME,https://www.nasdaq.com/articles/bitcoin-stocks...,"The price of bitcoin, the oldest and largest c...",bitcoin,100.0
12,2023-09-13 00:00:00 UTC,"""Blockbuster Status"": 3 Bios to Buy and Hold",ABBV,https://www.nasdaq.com/articles/blockbuster-st...,Profitability in the Biotech Industry is Hard ...,chatgpt,100.0
13,2019-11-15 00:00:00 UTC,"""Borderlands 3"" and ""Outer Worlds"" Will Help T...",TTWO,https://www.nasdaq.com/articles/borderlands-3-...,When most people think of Take-Two Interactive...,grand theft auto v,100.0
17,2022-03-24 00:00:00 UTC,"""Chip Rally,"" NATO Results, Drive Market Indexes",NVDA,https://www.nasdaq.com/articles/chip-rally-nat...,Markets kept their early morning gains and — a...,nato,100.0
23,2016-06-23 00:00:00 UTC,"""Finding Dory"" Had a Record-Breaking $135.1 Mi...",CMCSA,https://www.nasdaq.com/articles/finding-dory-h...,Walt Disney Co. 's(NYSE: DIS) Finding Dory rak...,civil war,100.0
25,2018-06-02 00:00:00 UTC,"""Fortnite Battle Royale"" Is Taking the Video G...",EA,https://www.nasdaq.com/articles/fortnite-battl...,"Over the last decade, video game companies hav...",natural disaster,100.0
28,2014-11-04 00:00:00 UTC,"""Goodbye Mr. Jones"": The End Of The Dow As An ...",KO,https://www.nasdaq.com/articles/goodbye-mr-jon...,By The Intercollegiate Finance Journal :\nBy C...,the king,100.0
36,2020-12-05 00:00:00 UTC,"""If You Don't Have an Estate Plan, Please, Jus...",KSS,https://www.nasdaq.com/articles/if-you-dont-ha...,"In this episode of Motley Fool Answers, Alison...",chapter 11 bankruptcy,100.0
42,2019-06-04 00:00:00 UTC,"""Magic: The Gathering"" Found a Home in Netflix",HAS,https://www.nasdaq.com/articles/magic%3A-gathe...,The long-fought battle to make movies out of M...,rcep,100.0
49,2022-01-07 00:00:00 UTC,"""Motley Fool Money"" 2022 Investing Preview",NKE,https://www.nasdaq.com/articles/motley-fool-mo...,"What's so exciting about home improvement, hea...",riots,100.0
50,2023-01-04 00:00:00 UTC,"""Motley Fool Money"" 2023 Investing Preview",DEA,https://www.nasdaq.com/articles/motley-fool-mo...,"In this podcast, Motley Fool senior analysts J...",invasion,100.0
51,2022-12-03 00:00:00 UTC,"""Motley Fool Money"" Discusses Best Side Dishes...",DIS,https://www.nasdaq.com/articles/motley-fool-mo...,"In this podcast, Motley Fools Chris Hill, Bill...",murder,100.0
52,2022-09-07 00:00:00 UTC,"""Motley Fool Money"" Fall Preview for Investors",QCOM,https://www.nasdaq.com/articles/motley-fool-mo...,"In this podcast, Motley Fool senior analysts E...",olympics,100.0
53,2023-10-31 00:00:00 UTC,"""Motley Fool Money"" on the Road",NDAQ,https://www.nasdaq.com/articles/motley-fool-mo...,"In this podcast, Motley Fool host Dylan Lewis ...",avatar,100.0
55,2023-04-14 00:00:00 UTC,"""Natty"" Is Down Big. What Comes Next Is More E...",HP,https://www.nasdaq.com/articles/natty-is-down-...,"We contrarians, we're not ashamed to admit, ma...",european union,100.0
57,2020-02-10 00:00:00 UTC,"""Parasite"" Dominated the 2019 Oscars",T,https://www.nasdaq.com/articles/parasite-domin...,The results are in for the Academy Awards of 2...,academy award,100.0
59,2023-12-16 00:00:00 UTC,"""Pivot Party"" Keeps Holiday Season Rolling",CLF,https://www.nasdaq.com/articles/pivot-party-ke...,"It’s holiday season, so why not keep the party...",presidential election,100.0
64,2023-11-03 00:00:00 UTC,"""Reduce Excessive Credit Card Fees"": Why Visa ...",DFS,https://www.nasdaq.com/articles/reduce-excessi...,Congress is putting major credit card processo...,senate,100.0
67,2023-07-15 00:00:00 UTC,"""Rule Breaker Investing"" Market Cap Game Show:...",TSLA,https://www.nasdaq.com/articles/rule-breaker-i...,To catch full episodes of all The Motley Fool'...,european union,100.0
69,2022-10-29 00:00:00 UTC,"""Rule Breaker Investing"" October Mailbag: List...",AAPL,https://www.nasdaq.com/articles/rule-breaker-i...,In this mailbag edition of Rule Breaker Invest...,summit,100.0
70,2023-01-14 00:00:00 UTC,"""Rule Breaker Investing"": Old, New, Borrowed, ...",TSLA,https://www.nasdaq.com/articles/rule-breaker-i...,"In this podcast, Motley Fool co-founder David ...",moon,100.0
74,2016-05-09 00:00:00 UTC,"""Sheik""-Up in Saudi Oil Leadership",GS,https://www.nasdaq.com/articles/sheik-saudi-oi...,"Monday, May 9, 2016\nStocks are indicated to s...",the king,100.0
84,2019-10-18 00:00:00 UTC,"""Star Wars"" Galaxy's Edge: Why Disney Investor...",CMCSA,https://www.nasdaq.com/articles/star-wars-gala...,Comcast (NASDAQ: CMCSA) raised the bar for att...,avatar,100.0
86,2016-01-08 00:00:00 UTC,"""Star Wars: The Force Awakens"" Just Hit a Huge...",CMCSA,https://www.nasdaq.com/articles/star-wars-forc...,Star Wars: The Force Awakens\nAs if there were...,avatar,100.0
87,2019-10-23 00:00:00 UTC,"""Star Wars: The Rise of Skywalker"" Has Already...",DIS,https://www.nasdaq.com/articles/star-wars%3A-t...,"From the beginning, there was little doubt tha...",avatar,100.0
97,2019-07-27 00:00:00 UTC,"""The Lion King"" Extends Disney's Box Office Reign",DIS,https://www.nasdaq.com/articles/the-lion-king-...,It's been harder than ever to get Americans to...,avatar,100.0
99,2023-08-05 00:00:00 UTC,"""The Ride of a Lifetime"" Book Club",COST,https://www.nasdaq.com/articles/the-ride-of-a-...,For the latest edition of the Motley Fool Mone...,olympics,100.0
101,2023-06-22 00:00:00 UTC,"""US climate change lawsuit seeks $50 billion, ...",CVX,https://www.nasdaq.com/articles/us-climate-cha...,By Clark Mindock\nJune 22 (Reuters) - An Orego...,wildfire,100.0
104,2021-12-14 00:00:00 UTC,#AMC500K Takes Over Twitter as AMC Stock Bulls...,GME,https://www.nasdaq.com/articles/amc500k-takes-...,"InvestorPlace - Stock Market News, Stock Advic...",moon,100.0
105,2021-04-22 00:00:00 UTC,#AMCDAY: 8 Things for AMC Investors to Know Ab...,GME,https://www.nasdaq.com/articles/amcday%3A-8-th...,"InvestorPlace - Stock Market News, Stock Advic...",moon,100.0
107,2020-06-02 00:00:00 UTC,#BlackOutTuesday sweeps social media as U.S. s...,EBAY,https://www.nasdaq.com/articles/blackouttuesda...,"Recasts; adds Twitter trends, comments\nJune 2...",protest,100.0
109,2013-12-31 00:00:00 UTC,#PreMarket Primer For December 31: Last Day Of...,PRGO,https://www.nasdaq.com/articles/premarket-prim...,"In 2013, world markets have seen record highs ...",european union,100.0
110,2013-12-11 00:00:00 UTC,#PreMarket Primer for December 11: US Governme...,PRGO,https://www.nasdaq.com/articles/premarket-prim...,"On Tuesday, US policymakers announced a bipart...",protest,100.0
111,2013-12-13 00:00:00 UTC,#PreMarket Primer for December 13: Budget Wars...,GE,https://www.nasdaq.com/articles/premarket-prim...,The US government's bipartisan budget deal eas...,house of representatives,100.0
112,2013-11-18 00:00:00 UTC,#PreMarket Primer for November 18: Progress Wi...,TSN,https://www.nasdaq.com/articles/premarket-prim...,Recent negotiations between the US and Iran co...,israel,100.0
113,2013-11-26 00:00:00 UTC,#PreMarket Primer for November 26: McMillon Se...,CBRL,https://www.nasdaq.com/articles/premarket-prim...,Doug McMillon will replace Mike Duke as CEO of...,senate,100.0
114,2013-11-27 00:00:00 UTC,#PreMarket Primer for November 27: Some US Ret...,HPQ,https://www.nasdaq.com/articles/premarket-prim...,With several large retail chains planning to b...,chancellor,100.0
115,2014-04-11 00:00:00 UTC,"#PreMarket Primer: Friday, April 11: Tension B...",AA,https://www.nasdaq.com/articles/premarket-prim...,"On Thursday, Russian President Vladimir Putin ...",senate,100.0
116,2014-04-25 00:00:00 UTC,"#PreMarket Primer: Friday, April 25: More Sanc...",CAT,https://www.nasdaq.com/articles/premarket-prim...,Rising tension in Ukraine weighed on markets a...,diplomatic,100.0

In [ ]:
df = pd.read_csv("filtered_news/filtered_news_with_keywords_v2.csv")

In [10]:
df["Article"]

0        If you're a longtime listener to this podcast,...
1        We've already gotten comfortable with digital ...
2        Some investors "aped" into AMC Entertainment (...
3        In this video, I will talk about Walt Disney (...
4        Almost since its record-setting debut, Avenger...
                               ...
82368    For many, competing in the Olympics is the pin...
82369    InvestorPlace - Stock Market News, Stock Advic...
82370    InvestorPlace - Stock Market News, Stock Advic...
82371    InvestorPlace - Stock Market News, Stock Advic...
82372    InvestorPlace - Stock Market News, Stock Advic...
Name: Article, Length: 82373, dtype: object